### ISSUE TITLE
smfish

### ISSUE THREAD

**Issue by Chengwei94** [Teichlab/Pan_fetal_immune#59]
Hi there, may I know where I can find the smfish validation data and also the gut visium data? Thanks!

**Comment by emdann** [comment]
Hi @Chengwei94, thank you for flagging these missing links!
The gut data was published with a different study (https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-10386/). We are working to add the preprocessed gut files with c2l mapping to our web portal. As for the smFISH data, we are still in the process of submitting this data to the BioImage archive. I'll add the links to the README as soon as they are ready.

I expect these uploads to be ready in 1-2 weeks at the latest. If you need to use this data more urgently than that, please get in touch via email (ed6<at>sanger.ac.uk) and we can arrange a file transfer.

**Comment by emdann** [comment]
Find the smFISH data here https://www.ebi.ac.uk/biostudies/studies/S-BIAD515

**Comment by Chengwei94** [comment]
Thanks!
